services:
  - type: web
    name: crosh-backend
    env: docker
    dockerfilePath: ./apps/backend/Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: S3_ENDPOINT
        sync: false
      - key: S3_REGION
        sync: false
      - key: S3_ACCESS_KEY_ID
        sync: false
      - key: S3_SECRET_ACCESS_KEY
        sync: false
      - key: S3_BUCKET
        sync: false
      - key: S3_PUBLIC_BASE_URL
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: EMAIL_FROM
        sync: false

  - type: web
    name: crosh-frontend
    env: docker
    dockerfilePath: ./apps/frontend/Dockerfile
    envVars:
      - key: NEXT_PUBLIC_API_URL
        sync: false